import os
import json
import http.client
from dotenv import load_dotenv

# Load environment variable and get API key
load_dotenv()
api_key = os.getenv("GEMINI_API_KEY") or exit("Error: GEMINI_API_KEY not found")

# Request body (JSON)
data = {
    "contents": [{
        "parts": [{"text": "Translate to Romanian: 'Hello, how are you?'"}]
        }]
}

# Convert data to JSON
json_data = json.dumps(data)

# Create connection and send the request
conn = http.client.HTTPSConnection("generativelanguage.googleapis.com")
conn.request("POST", f"/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}",
             body=json_data,
             headers={'Content-Type': 'application/json'})

# Get the response
response = conn.getresponse()
response_data = json.loads(response.read().decode("utf-8"))

# Display the generated text
print("Response generated by API:", response_data["candidates"][0]["content"]["parts"][0]["text"])

# Close the connectionF
conn.close()
